---

enableGlobDot: true

patterns:
  - name: GithubUser
    pattern: /\[@.+\]/gmx
  - name: MarkdownCode
    pattern: /`{1,3}.+`{1,3}/gmx
  - name: MarkdownCodeBlock
    pattern: /^\s*```[\s\S]*?^\s*```/gmx

languageSettings:
  - languageId: markdown
    ignoreRegExpList:
      - Email
      - GithubUser
      - MarkdownCode
      - MarkdownCodeBlock

words:
  - Gitter
  - Trotsenko
  - Vladislav
  - bestwebua
  - codebases
  - dockerhub
  - dockerized
  - healthcheck
  - truemail
